### ISSUE TITLE
Still maintained? Dead?

### ISSUE THREAD

**Issue by TheNomad11** [radgeek/feedwordpress#107]
Obvious question after no updates for nearly two years. Is this excellent plugin still maintained or is it dead?

**Comment by radgeek** [comment]
At the risk of insisting that it's really just pining for the fjords, what I'll say is this: I have changed job situations a couple times in the last two years in ways that have made it difficult for me to devote much time to the project.

But I do have my daily schedule and professional situation pretty much settled now, which should allow me the chance to finally carve out some more time for ongoing work, and I **do** still have plans to resume more active development and push out at least a couple new updates. Hopefully in early-mid summer.

If it doesn't happen by the end of the year, then it's a safe bet that it's probably not going to happen. But I **am** earnestly expecting that it will start to happen within the next month. So, I guess, sorry for the long hiatus, but watch this space.

**Comment by TheNomad11** [comment]
Great, thanks. That was good to hear. There is no other plugin like this out there. Keep up the good work!

**Comment by littlebytesnews** [comment]
I'm hopeful this is true even though this is already a few months old. I've been using your feed WordPress plugin for quite sometime but lately it has come to my attention that it is causing my WordPress site to crash lately. Here is the recent error I received:
FWP+: Add Attribution
Disable while troubleshooting
enable FeedWordPress to add a prefix or a suffix to elements of syndicated posts, containing attribution information

Version 2016.0506 | By Charles Johnson | Visit plugin site
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_ERROR was caused in line 396 of the file /home/littl438/public_html/wp-content/plugins/radgeek-FWP---Add-Attribution-70acf52/add-attribution-feedwordpress.php. Error message: Uncaught Error: Call to undefined function is_syndicated() in /home/littl438/public_html/wp-content/plugins/radgeek-FWP---Add-Attribution-70acf52/add-attribution-feedwordpress.php:396 Stack trace: #0 /home/littl438/public_html/wp-content/plugins/radgeek-FWP---Add-Attribution-70acf52/add-attribution-feedwordpress.php(421): add_source_information_simple('title', 'GDPR Compliance...', 1347502) #1 /home/littl438/public_html/wp-includes/class-wp-hook.php(286): add_source_information_title('GDPR Compliance...', 1347502) #2 /home/littl438/public_html/wp-includes/plugin.php(208): WP_Hook->apply_filters('GDPR Compliance...', Array) #3 /home/littl438/public_html/wp-includes/post-template.php(165): apply_filters('the_title', 'GDPR Compliance...', 1347502) #4 /home/littl438/public_html/wp-includes/link-template.php(4359): get_the_title(Object(WP_Post)) #5 /home/littl438/public_html/wp-includes/link-template.php(4341): get_the_privacy_policy_link('

Select All

**Comment by TheNomad11** [comment]
> Version 2016.0506 | By Charles Johnson | Visit plugin site
> This plugin failed to load properly and is paused during recovery mode.

 @littlebytesnews  your plugin is out of date, there is a newer version of it: Version 2017.1020

**Comment by GwynethLlewelyn** [comment]
Also note that there continues to be very active development here on GitHub — I guess that @radgeek is just waiting for enough fixes/changes to be added to the code to publish a new release on the official WordPress plugin repository.

**Comment by radgeek** [comment]
@GwynethLlewelyn : the development up through New Years' is mostly not to my credit -- I'd just been merging in pull requests from other developers to handle particular issues. But your assessment is basically accurate -- in particular, I was waiting to take some time out to do at least some preliminary compatibility testing with recent versions of WordPress, so that I could update the "Tested up to" flag when pushing updates to the WordPress plugin repository.

In any case -- as y'all may have noticed, in addition to the updates pushed here to Github, I have rolled up changes up to the present and pushed version 2020.0118 to the WordPress plugin repository, here: https://wordpress.org/plugins/feedwordpress/ . I am continuing work and doing additional testing, as well as trying to get documentation updated; there should be some more point releases late this month or early next.

**Comment by TheNomad11** [comment]
Thanks so much for this update, @radgeek I just saw it and am happy!
