### ISSUE TITLE
Fatal error when activating feedwordpress

### ISSUE THREAD

**Issue by JJ** [radgeek/feedwordpress#11]
I get this error when installing the feed on 3.5.1, latest version 2013.0502

```
Warning: require_once(/path/to/install/wp-content/plugins/feedwordpress/externals/myphp/myphp.class.php) [function.require-once]: failed to open stream: No such file or directory in /path/to/install/wp-content/plugins/feedwordpress/feedwordpress.php on line 105
```

It obviously does not activate after that.

**Comment by tekaymedia** [comment]
@radgeek I'm experiencing the same problem. I guess with your latest update. It broke my WP website and I had to manually deactivate the plugin. When I want to activate it again I get the error message on the plugins page.

**Comment by radgeek** [comment]
@tekaymedia Just to be clear, the problem you got is that you got a fatal PHP error after updating the plugin to version 2016.1211 (the version released a couple days ago)?

If you are using FWP with a WordPress version < 4.7, then you should be able to fix the problem by updating to the latest release of FWP, 2016.1213, which I just pushed to Github and to the WordPress plugins repository, which should restore backwards compatibility with versions of WordPress < 4.7. Take a look and let me know if it solves your problem. If so, great; and I'm sorry for the trouble with the last update. If not, let me know in more detail what you're seeing when you try to activate the new version, and I'll do what I can to troubleshoot.

**Comment by tekaymedia** [comment]
Solved! Updating to the latest version of FWP fixed the problem. Now running on WP 4.7. Thanks!
