### ISSUE TITLE
PHP 7.4 Deprecated: Function get_magic_quotes_gpc()

### ISSUE THREAD

**Issue by ThatStevensGuy** [radgeek/feedwordpress#119]
In PHP 7.4 get_magic_quotes_gpc() has been deprecated.

Deprecated: Function get_magic_quotes_gpc() is deprecated in /wp-content/plugins/feedwordpress/externals/myphp/myphp.class.php on line 36

https://www.php.net/manual/en/function.get-magic-quotes-gpc.php

My fix was to just comment out that if statement on line 36.

**Comment by radgeek** [comment]
This should be fixed by the most recent release, 2020.0818. Thanks for the report!
