### ISSUE TITLE
Database error when feedwordpress activated

### ISSUE THREAD

**Issue by ericvanderlinden** [radgeek/feedwordpress#14]
When i create a URL for a tag (/tag/seoul/ or /?tag=seoul) i get this error:

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1]
SELECT SQL_CALC_FOUND_ROWS wp_posts.ID FROM wp_posts INNER JOIN wp_term_relationships ON (wp_posts.ID = wp_term_relationships.object_id) WHERE 1=1 AND ( wp_term_relationships.term_taxonomy_id = 182

The closing ) is missing from the query. This only happens with feedwordpress activated.

**Comment by radgeek** [comment]
I'm closing this issue out because it pertains to an option which was a bad idea in the first place when I added it, and which I've since removed from FeedWordPress, and so should be fixed thereby. Happily it should no longer be possible to run into this problem
