### ISSUE TITLE
feedwordpressdiagnostic.class.php on line 82

### ISSUE THREAD

**Issue by SimcaCZE** [radgeek/feedwordpress#142]
Hello, I have Multisite wordpress. I can not use your plugin.
Error code - parameter 2 to be array, string given in l/www/wp-content/plugins/feedwordpress-master/feedwordpressdiagnostic.class.php on line 82

My php PHP 7.4
Thanks for reply

**Comment by GwynethLlewelyn** [comment]
Try using commit #[3315157] (https://github.com/radgeek/feedwordpress/commit/33151570de32c2e0b3595970426149951de1a467) :-) I remember that this was one of the many things that I also encountered and supposedly fixed...

**Comment by jhaeger** [comment]
Having the same problem!

**Comment by jhaeger** [comment]
However, php 8.2, and feedwordpress has not been updated in quite some time.

**Comment by radgeek** [comment]
I believe that this issue should be resolved by the most recent update (Version 2024.0511). If not, let me know the error message you are now seeing with line number and I'll take a look.
