### ISSUE TITLE
The Plugin "FeedWordPress" has been removed from wordpress.org but is still installed on your site.

### ISSUE THREAD

**Issue by svandragt** [radgeek/feedwordpress#149]
Hello there, longtime user of this plugin which I'm using to pull all my rss feeds into a master one.

I got this notification from WordFence and I wonder if you can give a status update, is this temporary or perhaps you need maintainance support? Anything a fellow developer can help with?

> This means that a plugin is no longer available to install from WordPress.org. Plugins can be removed from WordPress.org for a variety of reasons, including that the author intentionally stopped its development or converted it to a “paid only” plugin. A plugin can also be removed if it violates the WordPress.org terms of service, or if it contains vulnerabilities. If it contains vulnerabilities, it may be restored to the repository within a few days.

**Comment by david-robinson-practiceweb** [comment]
This could be related to #148 
@radgeek I assume that https://github.com/radgeek/feedwordpress/commit/3bdcfa7d5ebe850918b129972de34a04bda81425 is the fix for that.
Is there a release pending for this or extra steps you might have to take due to the action on the plugin page?

**Comment by radgeek** [comment]
Hey all, thanks for reaching out. The temporary closure of the repository was related to #148 as @david-robinson-practiceweb figured. The issue should be resolved in the most recent release of FeedWordPress (2024.0428), which is available either with a pull from this here repository, or from the (now-reopened) WordPress Plugin Repository copy.
