### ISSUE TITLE
Prevent fwp to create manual excerpts

### ISSUE THREAD

**Issue by tipshunter** [radgeek/feedwordpress#34]
I just want my theme to rely on automatic excerpts. Is there a hook to use to apply some kind of filter?

**Comment by garyblankenship** [comment]
```
//* strip the syndicated excerpt
add_filter( 'syndicated_item_excerpt', function ( $excerpt ) {
	return '';
} );
```

**Comment by radgeek** [comment]
Hi @tipshunter 

As @garyblankenship  suggests above, the filter hook to use to control the post exerpt for a syndicated item is `syndicated_item_excerpt` 

Your filtering function should ideally take two parameters: one a string containing the current state of the post excerpt at the time of filtering, and a second which refers to the SyndicatedPost object. It should return a string value, containing the excerpt that you want FeedWordPress to use, including any modifications that you wanted to make. If you want to get an excerpt from WordPress's default excerpting method, then you should return a blank string. So something like this:

~~~
add_filter( 'syndicated_item_excerpt', function ( $excerpt, $post ) {
    return '';
}, 10, 2);
~~~

HTH. If you have any questions or need any help getting this to work for you, let me know.
