### ISSUE TITLE
Considering Tags as Categories

### ISSUE THREAD

**Issue by aledr** [radgeek/feedwordpress#37]
FeedWordPress is creating categories with tags names instead of categories.

Thanks.

**Comment by ideadapt** [comment]
I have the same problem. It makes the plugin practically useless.

FeedWordPress 2016.0420, Wordpress 4.6.1.

I think this problem has existed for a longer time. Does anyone have any idea why this is? Does everyone have this?

**Comment by aledr** [comment]
I am closing as stale after seven years.
