### ISSUE TITLE
Potential XSS issue with add_query_arg() and remove_query_arg()

### ISSUE THREAD

**Issue by quassy** [radgeek/feedwordpress#39]
As you may know quite recently there was news that WordPress plugins could suffer from a XSS vulnerability if they use [`add_query_arg()`](https://developer.wordpress.org/reference/functions/add_query_arg/) and [`remove_query_arg()`](https://developer.wordpress.org/reference/functions/remove_query_arg/) without properly sanitizing the data. When the optional third parameter of these functions is omitted, `$_SERVER['REQUEST_URI']` is used unescaped, [more info here](https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/).

Checking your source it seems the functions are used in the following lines of feedwordpress.php:
* [1287](https://github.com/radgeek/feedwordpress/blob/master/feedwordpress.php#L1287)
* [1327](https://github.com/radgeek/feedwordpress/blob/master/feedwordpress.php#L1327)
* [1339](https://github.com/radgeek/feedwordpress/blob/master/feedwordpress.php#L1339)

I am not actually sure if FeedWordPress is vulnerable but I think it should be looked at and `esc_url()` or `esc_raw_url()` be added.

**Comment by talgalili** [comment]
Hi Quassy,
Do you know if WP 4.1.3 is immune to this issue?

**Comment by quassy** [comment]
I don't think so. As I understand it the two functions were never meant to escape their inputs / outputs. It was a bug in the documentation which led plugin developers to falsely assume it does and resulted in implementing this security hole unknowningly.

> Background: Due to a now-fixed ambiguity in the documentation for the add_query_arg() and remove_query_arg() functions, many plugins were using them incorrectly, allowing for potential XSS attack vectors in their code.

Release notes / blog posts of [4.2](codex.wordpress.org/Version_4.2) and [4.1.3](http://codex.wordpress.org/Version_4.1.3) don't mention that the issue was fixed, while [4.1.2](https://wordpress.org/news/2015/04/wordpress-4-1-2/) mentions it and calls on developers to fix their plugins.

**Comment by talgalili** [comment]
VERY risky stuff.
Since radgeek does not update the plugin often, any chance you'd know how to fix this?

**Comment by quassy** [comment]
I am by no means a WordPress or plugin developer, so take this with two spoons of salt and pepper!... I don't actually know what's happening with $sendback at line 1287. I have the feeling the variable is only declared to never be used again, so what's the point? Still I would change the line to

    $sendback = esc_url( remove_query_arg( array('trashed', 'untrashed', 'deleted', 'zapped', 'unzapped', 'ids'), $sendback ) );

1327:

    wp_redirect( esc_url_raw( add_query_arg( array('zapped' => 1, 'ids' => $post_id), $sendback ) ) );

1339: 

    wp_redirect( esc_url_raw( add_query_arg( array('unzapped' => 1, 'ids' => $post_id), $sendback ) ) );

So basically adding ´esc_url()´ every time the URL might be printed somewhere and adding ´esc_url_raw()´ every time the URL is used for a header.

**Comment by talgalili** [comment]
Well, let's hope someone who knows more then both of us will give this a look :)

Thank you very much for the report! :+1:
