### ISSUE TITLE
Jetpack's "related posts" feature does not work with syndicated posts

### ISSUE THREAD

**Issue by talgalili** [radgeek/feedwordpress#41]
Here it doesn't work:
http://www.r-bloggers.com/how-to-install-rnomads-with-grib-file-support-on-windows/

Here is does (a post of the site, not syndicated)
http://www.r-bloggers.com/doing-quantitative-archaeology-with-open-source-software/

Any ideas why this is happening?

**Comment by garyblankenship** [comment]
Jetpack's related posts is using a content filter.  Feedwordpress disables them by default.  You can restore this.

Syndication > Posts & Links > Formatting
Formatting filters: Expose syndicated posts to formatting filters.

**Comment by talgalili** [comment]
PERFECT - thank you @garyblankenship
