### ISSUE TITLE
Fatal error: Call to a member function uri() on a non-object in feedwordpress-master/admin-ui.php on line 68

### ISSUE THREAD

**Issue by TimMarshAU** [radgeek/feedwordpress#46]
When clicking Update Now button after mapping a feed to a category, I get this error.

Fatal error: Call to a member function uri() on a non-object in /home/ufuaasna/public_html/ufutas/site/wp-content/plugins/feedwordpress-master/admin-ui.php on line 68

**Comment by radgeek** [comment]
Thanks for the heads-up on the issue. Sorry about that! I just committed a change to the master branch that should fix the issue (2f05ca7f4a6a43fc987c5a5a6e21dd5713fa15f0). Check it out and let me know if it solves the issue on your end. ~C

**Comment by TimMarshAU** [comment]
Hi, looks good! Was this pushed to the Wordpress repository too? I got an update notification (the widespread XSS vulnerability), updated, clicked Update, looks good!
