### ISSUE TITLE
Undefined variable $record in search() in sydicatiedpostterm.class.php line 93

### ISSUE THREAD

**Issue by hughiemolloy** [radgeek/feedwordpress#50]
This gets called every time a posts imported.

**Comment by radgeek** [comment]
Thanks for catching this. I checked the code causing the problem and fortunately, the won't harm functionality at all; it is simply a matter of a status message depending on a variable that had previously existed in that method, but then later was moved to a different method. I'll make a change that will suppress the warning message you're seeing when I get home later this afternoon.

**Comment by radgeek** [comment]
This should be fixed by https://github.com/radgeek/feedwordpress/commit/d826202f07728c36eaea1356ee205931c9df8c55

**Comment by hughiemolloy** [comment]
Brilliant thanks.

*Hughie Molloy*

*Kaldor Ltd - Winner of AOP's One to Watch award*
143 Long Acre, London WC2E 9AD
+44 203 4055231

www.pugpig.com
@pugpig
