### ISSUE TITLE
The feed stopped working after WordPress 4.6.1 Update

### ISSUE THREAD

**Issue by psolovyov** [radgeek/feedwordpress#68]
"The data could not be converted to UTF-8. You MUST have either the iconv or mbstring extension installed. Upgrading to PHP 5.x (which includes iconv) is highly recommended."

Running PHP Version 5.5.9, both iconv and mbstring are installed. 

On dev server that is running WordPress 4.5.3 it works without any issues.

**Comment by radgeek** [comment]
I'm sorry not to get back to you about this issue at the time you posted it; this is almost certainly a local configuration issue, either with your web hosting environment or with the feed you are trying to syndicate. If you are running into an issue like this now, please do feel free to reopen or to [contact me via e-mail](https://fwpplugin.com/contact/) with some details, preferably the version numbers for everything reported in `Syndication > Diagnostics`, the output of `phpinfo()` if you are able to access that, and the URL(s) of the feed(s) that is/are giving you this error message, and I can try to dig in in more detail to see what's going on.
