### ISSUE TITLE
Getting error: Non-static method FeedWordPress::update_requested()

### ISSUE THREAD

**Issue by sckott** [radgeek/feedwordpress#70]
My setup:
- FeedWordPress version 2016.0614. (latest from master of this repo)
- Hosting Environment:  
  - WordPress: version 4.6.1
  - PHP: version 7.0.8-0ubuntu0.16.04.3
  - Web Server: Apache/2.4.18 (Ubuntu)

On trying to update from any feed I'm getting:

> Deprecated: Non-static method FeedWordPress::update_requested() should not be called statically in /var/www/coffeehouse.dataone.org/htdocs/wp-content/plugins/feedwordpress-master/feedwordpress.php on line 2313

And same message but for line 2318. Those lines:

https://github.com/radgeek/feedwordpress/blob/30028f935b96369a79267865239a0dcfa7459031/feedwordpress.php#L2313
https://github.com/radgeek/feedwordpress/blob/30028f935b96369a79267865239a0dcfa7459031/feedwordpress.php#L2318

Curious if you know if this is something I should fix in my wordpress setup, maybe i'm on a ubuntu or php version that doesn't work with this plugin, OR is it maybe a bug in the plugin?

**Comment by radgeek** [comment]
Thanks for the heads-up on this notice. I believe that this issue should be resolved as of the most recent release of FeedWordPress, 2016.1213. Anyway, take a look and let me know if pulling from origin fixes it for you.

**Comment by sckott** [comment]
works now, thanks :)
