### ISSUE TITLE
Flattr http javascript src loaded in wp-admin

### ISSUE THREAD

**Issue by stedaniels** [radgeek/feedwordpress#73]
The flattr javascript is being loaded (attempted) over http in wp-admin, not sure if elsewhere, but definitely here.  This fails due to being loaded over https.  https://github.com/radgeek/feedwordpress/pull/72 is a minor pull request to fix this issue.

**Comment by radgeek** [comment]
(Thanks! This was fixed a while back by merging #72 into the main branch.)
