### ISSUE TITLE
Store images from a feed rss locally

### ISSUE THREAD

**Issue by diogopms** [radgeek/feedwordpress#74]
I would like to know if anyone have a plan to add a feature to store images in locally instead of Feed RSS (I don't want to load the images from Feed RSS).

If not possible, i will try to open a PR with that feature.

**Comment by radgeek** [comment]
Hi, thanks for checking in on this, hope I can help.

What you're looking for is *probably* implemented in this optional add-on. (Of course, details about how the local storage happen, etc. may be a bit different from what you had in mind, so let me know how well it fits your desired use-case.) <https://github.com/radgeek/FWP---SIC--Em>

I'm going to provisionally mark this as Closed, but if you have any questions or if the add-on doesn't do what you want, feel free to check in with me about that and I will reopen.
