### ISSUE TITLE
Call to a member function setting() on a non-object

### ISSUE THREAD

**Issue by thegreatmichael** [radgeek/feedwordpress#75]
Wordpress v 4.6.1
FWP: Version 2016.0420

When I click on a link in my blog that is a post that has been syndicated from a source I get: 

`Fatal error: Call to a member function setting() on a non-object in /<mypath>/wp-content/plugins/feedwordpress/feedwordpress.php on line 613`

**Comment by thegreatmichael** [comment]
perhaps it's due to http://feedwordpress.radgeek.com/wiki/get_syndication_feed_object/comment-page-1/#comment-1294113

**Comment by radgeek** [comment]
(Thanks, this should be fixed in the current version of FWP by the pull request / merge linked above.)
