### ISSUE TITLE
Feedwordpress generates warning after WordPress 4.7 upgrade

### ISSUE THREAD

**Issue by danyork** [radgeek/feedwordpress#76]
Hello! Thank you for continuing to maintain this excellent plugin.  FYI, after upgrades today to WordPress 4.7, multiple users are reporting a problem that generates this warning message throughout the admin screens:

>  Warning: Parameter 1 to FeedWordPressHTTPAuthenticator::set_auth_options() expected to be a reference, value given in /home/danyork/public_html/wp-includes/class-wp-hook.php on line 300

These reports can be seen here:

https://wordpress.org/support/topic/broken-with-the-wordpress-4-7-update/

One person in the conversation reported a potential workaround:

----

Ok, so it’s very likely the wrong answer, but I removed the ampersand before the $handle parameter for FeedWordPressHTTPAuthenticator::set_auth_options() in feedwordpresshttpauthenticator.class.php and the error disappeared (and my feed imports still worked). 

----

And others in the feed, and myself, can confirm that this works to remove the warning message.  I don't know, though, and I suspect others don't know, what this has actually done.

**Comment by cogdog** [comment]
I have been doing the same fix, and am seeing fatal errors in @radgeek other plugins: FWP--Sic--EM and FWP-Add-Attribution

**Comment by cogdog** [comment]
Thanks for the update (via wordpress.org) @radgeek -- I cannot seem to reproduce the errors again (using the fix by @danyork). My copy of FWP--Sic--EM was out of date, and it seems to be fine with the updated one.  The error on FWP-Add-Attribution was after I had disabled FWP--Add-Attribution (error for call to is_syndicated() function). AM continuing to test on a few other non critical sites.

**Comment by radgeek** [comment]
Thanks y'all. I'm going to do some ongoing testing to make sure that there are no untoward side-effects of the change, but for the moment, I went ahead and published a quick compatibility fix similar to what @danyork quotes from the WordPress.org issue thread. So this should be fixable by grabbing the most recent version of FWP, either from Github or from the WordPress plugins repository.

If you notice any problems with updating feeds under the new version (especially any feeds you may have that make use of HTTP Authentication), let me know and I'll reopen the issue.

**Comment by netdragonboberb** [comment]
This strangely only started happening for me when I switched from php-fpm to mod-php

**Comment by netdragonboberb** [comment]
Slightly off-topic, but maybe helpful. I had the other error mentioned in that topic (copied below), but only after switching from php-fpm to mod-php5

Warning: call_user_func_array() expects parameter 1 to be a valid callback, no array or string given in /home/www/web411/html/bjoern/wp/wp-includes/class-wp-hook.php on line 298
