### ISSUE TITLE
[Q] Truncate option

### ISSUE THREAD

**Issue by sokai** [radgeek/feedwordpress#85]
Hey!

1st: I love your PlugIn! :-)
2nd: I wish/wanna have an option to truncate the re-published post(s). – May that possible?

Thanks a lot and best regards!

**Comment by radgeek** [comment]
Hey there,

Currently, the best way to do this is to make use of an add-on installed alongside FeedWordPress. In particular, I have a free add-on module called **FWP+: Limit size of posts**, which I think should allow you to do more or less exactly what you are looking to do. Take a look here: <https://github.com/radgeek/fwp-limit-size-of-posts> and let me know if it helps out with what you need. If you have any questions about getting it installed and configured, just drop me a line.

-C
