### ISSUE TITLE
Featured Image

### ISSUE THREAD

**Issue by BoxMediaUK** [radgeek/feedwordpress#89]
Is there a way to pull fist image in the post as load as featured image?

**Comment by radgeek** [comment]
Hey there,

Currently, the best way to do this is to make use of an add-on installed alongside FeedWordPress. In particular, I have a free add-on module called FWP+: SIC 'Em (Syndicated Image Cacher), which I think should allow you to do more or less exactly what you are looking to do. Take a look here: https://github.com/radgeek/FWP---SIC--Em and let me know if it helps out with what you need. If you have any questions about getting it installed and configured, just drop me a line.

-C
