### ISSUE TITLE
Mark FWP-generated users as such

### ISSUE THREAD

**Issue by boonebgorges** [radgeek/feedwordpress#90]
FWP generates users to correspond to incoming feed items when no existing user can be found in the database ( `SyndicatedPost::author_id()` ). These autogenerated users can clutter up certain parts of the interface, especially when using plugins like BuddyPress that provide networkwide listings of users: FWP users may not correspond to actual members, or they may duplicate actual members that are registered using different email addresses. 

As such, it'd be nice to filter these users out from various parts of the interface. But there's currently (so far as I can tell) to way to determine whether a given user has been created by FWP. A simple piece of usermeta would do the trick: `add_user_meta( $id, 'feedwordpress_generated', 1 );` or something like that.

Thanks in advance for your consideration!

**Comment by radgeek** [comment]
This is a good point, and a good idea. I went ahead and implemented it in the development version here on Github; it should also be incorporated into the next public release on the WordPress plugins repository SVN. I went ahead and used the meta key "feedwordpress_generated," just like in your suggestion. Hope this helps!

**Comment by boonebgorges** [comment]
Excellent! Thanks very much, @radgeek
