### ISSUE TITLE
Warning: count(): in feedwordpress.php::885

### ISSUE THREAD

**Issue by slaFFik** [radgeek/feedwordpress#98]
> Warning: count(): Parameter must be an array or an object that implements Countable in /home/cosydale/public_html/createdby.it/wp-content/plugins/feedwordpress/feedwordpress.php on line 885

On Edit screen of the link added to WP, like this: `/wp-admin/link.php?action=edit&link_id=1`:

**Comment by davecampbell** [comment]
any idea if your fix would address this error that i get when my cron job runs to update all the syndications?
===
PHP Warning:  count(): Parameter must be an
array or an object that implements Countable in
/home/davecampbell/louisvillestream.com/startup/wp-content/plugins/feedwordpress/syndicatedlink.class.php
on line 302

**Comment by radgeek** [comment]
The issue should be resolved by the pull request merged on 27-Sep-2019. Let me know if you're still encountering anything like this.
